# Permalinks
permalink:           pretty

# Setup
title:               Olivier Binette
tagline:             Cielographie
url:                 http://olivierbinette.ca
paginate:            5
baseurl:             "/Cielographie"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

excerpt_separator: "<!--more-->"

# About/contact
author:
  name:              Olivier Binette
  url:               http://olivierbinette.ca
  email:             olivier.binette@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
